### ISSUE TITLE
Is there a way to read from Docker secret files?

### ISSUE THREAD

**Issue by EgidioCaprino** [caddy-dns/porkbun#8]
Hi all,

Is there a way to read `PORKBUN_API_KEY` and `PORKBUN_API_SECRET_KEY` from secret files created by Docker?

**Comment by SinisterSpatula** [comment]
Yes, I do it like this:
# docker-compose.yml
```yml
services:
  caddy:
    container_name: caddy
    build:
      context: ./
      target: caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORKBUN_API_KEY=${PORKBUN_API_KEY}
      - PORKBUN_API_SECRET_KEY=${PORKBUN_API_SECRET_KEY}
```
# .env file
```yml
PORKBUN_API_KEY="yourKeyHere"
PORKBUN_API_SECRET_KEY="youSecretKeyHere"
```
I place the .env file next to the compose file.  It reads the env and uses the values from .env file within the compose file.
